/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CryptoInfoListRelationFilter } from "../../cryptoInfo/base/CryptoInfoListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { FileContentListRelationFilter } from "../../fileContent/base/FileContentListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";

@InputType()
class FileInfoWhereInput {
  @ApiProperty({
    required: false,
    type: () => CryptoInfoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CryptoInfoListRelationFilter)
  @IsOptional()
  @Field(() => CryptoInfoListRelationFilter, {
    nullable: true,
  })
  cryptoInfos?: CryptoInfoListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => FileContentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FileContentListRelationFilter)
  @IsOptional()
  @Field(() => FileContentListRelationFilter, {
    nullable: true,
  })
  fileContents?: FileContentListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  fileName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  fileSize?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  uploadDate?: DateTimeNullableFilter;
}

export { FileInfoWhereInput as FileInfoWhereInput };
